name: Build and Push Docker Image to GHCR and Docker Hub

on:
  push:
    branches:
      - main # Ganti dengan branch yang Anda gunakan

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Penting untuk menulis ke GHCR

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # --- Langkah untuk GHCR ---
      - name: Login to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # GITHUB_TOKEN otomatis diberikan oleh GitHub

      - name: Set up Docker Buildx (untuk multi-platform build jika diperlukan)
        uses: docker/setup-buildx-action@v3

      - name: Determine image tag (gunakan SHA commit sebagai tag unik)
        id: meta_ghcr
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest,enable={{is-default}}
            type=sha

      - name: Build and push Docker image to GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta_ghcr.outputs.tags }}
          labels: ${{ steps.meta_ghcr.outputs.labels }}

      # --- Langkah untuk Docker Hub ---
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # GitHub Secret Anda
          password: ${{ secrets.DOCKER_PASSWORD }} # GitHub Secret Anda (atau DOCKER_TOKEN)

      - name: Determine Docker Hub image tag
        id: meta_dockerhub
        uses: docker/metadata-action@v5
        with:
          images: your-dockerhub-username/your-repo-name # Ganti dengan Docker Hub username/nama repo Anda
          tags: |
            type=raw,value=latest,enable={{is-default}}
            type=sha

      - name: Build and push Docker image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta_dockerhub.outputs.tags }}
          labels: ${{ steps.meta_dockerhub.outputs.labels }}
